import {useCallback,useEffect,useMemo,useState} from 'react';
import {ArrowRight,CreditCard,Eye,EyeOff,LoaderCircle,Plus,RefreshCw,WalletCards} from 'lucide-react';
import {useNavigate} from 'react-router-dom';
import api from '../../services/api';
import {useAuth} from '../../context/AuthContext';

const money=(v,c='INR')=>new Intl.NumberFormat('en-IN',{style:'currency',currency:c,maximumFractionDigits:2}).format(Number(v||0));
const mask=v=>v?`•••• •••• ${String(v).slice(-4)}`:'—';

export default function Accounts(){
 const {user}=useAuth(),navigate=useNavigate(),bankId=user?.bankId||user?.bank_id||'alpha';
 const [accounts,setAccounts]=useState([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(''),[hidden,setHidden]=useState(false);
 const load=useCallback(async(silent=false)=>{try{silent?setRefreshing(true):setLoading(true);setError('');const r=await api.get(`/banks/${bankId}/accounts`);setAccounts(r.data?.data?.accounts||[])}catch(e){setError(e.response?.data?.error?.message||'Unable to load your accounts.')}finally{silent?setRefreshing(false):setLoading(false)}},[bankId]);
 useEffect(()=>{load()},[load]);
 const total=useMemo(()=>accounts.reduce((s,a)=>s+Number(a.balance||0),0),[accounts]);
 return <main className="bank-page"><style>{css}</style><div className="wrap">
  <header className="top"><div><small>CUSTOMER BANKING</small><h1>My accounts</h1><p>View balances, account details and banking activity.</p></div><div className="actions"><button onClick={()=>load(true)} disabled={refreshing}><RefreshCw size={16}/> Refresh</button><button className="dark" onClick={()=>navigate('/accounts/new')}><Plus size={16}/> New account</button></div></header>
  {error&&<div className="error">{error}<button onClick={()=>load()}>Retry</button></div>}
  <section className="summary"><div><span>Total balance</span><strong>{loading?'—':hidden?'••••••':money(total/100)}</strong></div><div><span>Accounts</span><strong>{loading?'—':accounts.length}</strong></div><div><span>Active</span><strong>{loading?'—':accounts.filter(a=>String(a.status).toUpperCase()==='ACTIVE').length}</strong></div></section>
  <div className="privacy"><button onClick={()=>setHidden(v=>!v)}>{hidden?<Eye size={15}/>:<EyeOff size={15}/>} {hidden?'Show balances':'Hide balances'}</button></div>
  {loading?<div className="card empty"><LoaderCircle className="spin" size={30}/></div>:accounts.length===0?<div className="card empty"><WalletCards size={40}/><h3>No accounts yet</h3><p>Your bank accounts will appear here once created.</p></div>:<section className="grid">{accounts.map(a=><article className="card account" key={a.account_id}>
   <div className="account-head"><div className="account-title"><div className="icon"><CreditCard size={21}/></div><div><b>{a.account_type||'Account'}</b><small>{mask(a.account_number)}</small></div></div><em className={String(a.status).toUpperCase()==='ACTIVE'?'ok':'bad'}>{a.status||'UNKNOWN'}</em></div>
   <div className="balance">{hidden?'••••••':money(Number(a.balance||0)/100,a.currency||'INR')}</div><div className="meta"><div><small>IFSC</small><b>{a.ifsc_code||'—'}</b></div><div><small>CURRENCY</small><b>{a.currency||'INR'}</b></div></div>
   <button className="details" onClick={()=>navigate(`/accounts/${a.account_id}`)}>View account <ArrowRight size={16}/></button>
  </article>)}</section>}
 </div></main>
}
const css=`.bank-page{min-height:100vh;background:#f6f8fc;color:#172033;padding:32px}.wrap{max-width:1180px;margin:auto}.top{display:flex;justify-content:space-between;gap:20px;margin-bottom:25px}.top small{font-size:11px;font-weight:800;letter-spacing:.12em;color:#667085}.top h1{font-size:32px;margin:6px 0}.top p{margin:0;color:#667085}.actions{display:flex;gap:9px}.actions button,.details,.privacy button,.error button{border:1px solid #e4e7ec;background:#fff;border-radius:11px;padding:10px 14px;font-weight:750;cursor:pointer;display:flex;align-items:center;gap:7px}.actions .dark{background:#172033;color:#fff;border-color:#172033}.summary{display:grid;grid-template-columns:1.4fr 1fr 1fr;gap:15px;margin-bottom:10px}.summary,.card{ }.summary>div{background:#fff;border:1px solid #e7eaf0;border-radius:17px;padding:21px}.summary span{font-size:12px;color:#667085}.summary strong{display:block;font-size:27px;margin-top:6px}.privacy{display:flex;justify-content:flex-end;margin:0 0 12px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:17px}.card{background:#fff;border:1px solid #e7eaf0;border-radius:18px;box-shadow:0 5px 20px #10182808}.account{padding:21px}.account-head{display:flex;justify-content:space-between;gap:12px}.account-title{display:flex;gap:12px}.icon{width:44px;height:44px;border-radius:13px;background:#eef2ff;color:#3730a3;display:grid;place-items:center}.account-title b,.account-title small{display:block}.account-title small{color:#667085;margin-top:5px}.account-head em{font-style:normal;font-size:10px;font-weight:850;padding:6px 9px;border-radius:999px;height:max-content}.ok{background:#ecfdf3;color:#027a48}.bad{background:#fef3f2;color:#b42318}.balance{font-size:30px;font-weight:850;margin:24px 0}.meta{display:grid;grid-template-columns:1fr 1fr;gap:12px;border-top:1px solid #eef0f3;padding-top:15px}.meta small,.meta b{display:block}.meta small{font-size:10px;color:#98a2b3}.meta b{font-size:13px;margin-top:4px}.details{margin-top:18px;margin-left:auto}.empty{text-align:center;padding:55px 20px;color:#667085}.error{background:#fef3f2;border:1px solid #fecdca;color:#b42318;padding:13px 15px;border-radius:12px;margin-bottom:15px;display:flex;justify-content:space-between}.spin{animation:spin 1s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}@media(max-width:800px){.bank-page{padding:20px}.top{flex-direction:column}.actions button{flex:1;justify-content:center}.summary,.grid{grid-template-columns:1fr}}`;
