import {useCallback,useEffect,useState} from 'react';
import {ArrowDownLeft,ArrowLeft,ArrowUpRight,Check,Copy,CreditCard,Eye,EyeOff,LoaderCircle,ShieldCheck} from 'lucide-react';
import {useNavigate,useParams} from 'react-router-dom';
import api from '../../services/api';
import {useAuth} from '../../context/AuthContext';
const money=(v,c='INR')=>new Intl.NumberFormat('en-IN',{style:'currency',currency:c,maximumFractionDigits:2}).format(Number(v||0));
const mask=v=>v?`•••• •••• ${String(v).slice(-4)}`:'—';
export default function AccountDetails(){
 const {accountId}=useParams(),{user}=useAuth(),navigate=useNavigate(),bankId=user?.bankId||user?.bank_id||'alpha';
 const [account,setAccount]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[show,setShow]=useState(false),[copied,setCopied]=useState(false);
 const load=useCallback(async()=>{try{setLoading(true);setError('');const r=await api.get(`/banks/${bankId}/accounts/${accountId}`);setAccount(r.data?.data?.account||null)}catch(e){setError(e.response?.data?.error?.message||'Unable to load this account.')}finally{setLoading(false)}},[bankId,accountId]);
 useEffect(()=>{load()},[load]);
 const copy=async()=>{try{await navigator.clipboard.writeText(account.account_number);setCopied(true);setTimeout(()=>setCopied(false),1500)}catch{setError('Unable to copy account number.')}};
 if(loading)return <Shell><div className="card loading"><LoaderCircle className="spin" size={32}/> Loading account…</div></Shell>;
 if(error||!account)return <Shell><div className="card empty"><h2>Account unavailable</h2><p>{error||'Account not found.'}</p><button onClick={()=>navigate('/accounts')}> <ArrowLeft size={16}/> Back to accounts</button></div></Shell>;
 const active=String(account.status).toUpperCase()==='ACTIVE';
 return <Shell><style>{css}</style><div className="card">
  <div className="head"><div className="brand"><div className="icon"><CreditCard size={25}/></div><div><small>ACCOUNT DETAILS</small><h1>{account.account_type||'Bank Account'}</h1><p>{account.bank_name||bankId.toUpperCase()}</p></div></div><span className={active?'ok':'bad'}>{account.status}</span></div>
  <div className="hero"><small>AVAILABLE BALANCE</small><strong>{money(account.balance,account.currency||'INR')}</strong></div>
  <div className="info-grid"><Info label="Account number"><span className="number">{show?account.account_number:mask(account.account_number)}<button onClick={()=>setShow(v=>!v)}>{show?<EyeOff size={15}/>:<Eye size={15}/>}</button><button onClick={copy}>{copied?<Check size={15}/>:<Copy size={15}/>}</button></span></Info><Info label="IFSC">{account.ifsc_code||'—'}</Info><Info label="Currency">{account.currency||'INR'}</Info><Info label="Account ID">{account.account_id}</Info><Info label="Created">{account.created_at?new Date(account.created_at).toLocaleString('en-IN'):'—'}</Info><Info label="Security"><ShieldCheck size={15}/> Customer protected</Info></div>
  <div className="buttons"><button onClick={()=>navigate('/accounts')}><ArrowLeft size={16}/> Accounts</button><button disabled={!active} onClick={()=>navigate(`/transfer?accountId=${account.account_id}`)}><ArrowUpRight size={16}/> Transfer</button><button disabled={!active} onClick={()=>navigate(`/withdraw?accountId=${account.account_id}`)}><ArrowDownLeft size={16}/> Withdraw</button></div>
 </div></Shell>
}
function Info({label,children}){return <div className="info"><small>{label}</small><b>{children}</b></div>}
function Shell({children}){return <main style={{minHeight:'100vh',background:'#f6f8fc',padding:32,color:'#172033'}}><div style={{maxWidth:980,margin:'auto'}}>{children}</div></main>}
const css=`.card{background:#fff;border:1px solid #e7eaf0;border-radius:20px;padding:27px;box-shadow:0 6px 25px #1018280d}.loading,.empty{min-height:260px;display:grid;place-items:center;text-align:center}.head{display:flex;justify-content:space-between;gap:15px}.brand{display:flex;gap:14px}.icon{width:52px;height:52px;border-radius:15px;background:#eef2ff;color:#3730a3;display:grid;place-items:center}.brand small{font-size:11px;letter-spacing:.1em;font-weight:800;color:#667085}.brand h1{font-size:30px;margin:5px 0}.brand p{margin:0;color:#667085}.head>span{font-size:10px;font-weight:850;padding:7px 10px;border-radius:999px;height:max-content}.ok{background:#ecfdf3;color:#027a48}.bad{background:#fef3f2;color:#b42318}.hero{background:#111827;color:#fff;border-radius:16px;padding:22px;margin:26px 0}.hero small{opacity:.7;font-size:11px}.hero strong{display:block;font-size:36px;margin-top:5px}.info-grid{display:grid;grid-template-columns:1fr 1fr;gap:13px}.info{border:1px solid #edf0f4;border-radius:13px;padding:14px}.info small{display:block;font-size:10px;color:#98a2b3;text-transform:uppercase;letter-spacing:.05em}.info b{display:flex;gap:7px;align-items:center;margin-top:7px;word-break:break-word;font-size:13px}.number button{border:1px solid #e4e7ec;background:#fff;border-radius:7px;padding:5px;display:grid;place-items:center;cursor:pointer}.buttons{display:flex;gap:9px;margin-top:23px}.buttons button,.empty button{border:1px solid #e4e7ec;background:#fff;border-radius:10px;padding:11px 14px;font-weight:750;cursor:pointer;display:flex;align-items:center;gap:7px}.buttons button:not(:first-child){background:#172033;color:#fff;border-color:#172033}.buttons button:disabled{opacity:.45;cursor:not-allowed}.empty p{color:#667085}.spin{animation:spin 1s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}@media(max-width:700px){.head{flex-direction:column}.info-grid{grid-template-columns:1fr}.buttons{flex-direction:column}}`;
