import {useCallback,useEffect,useMemo,useState} from 'react';
import {ChevronLeft,ChevronRight,LoaderCircle,RefreshCw,Search,Wallet} from 'lucide-react';
import {useNavigate,useSearchParams} from 'react-router-dom';
import api from '../../services/api';import {useAuth} from '../../context/AuthContext';
const money=(v,c='INR')=>new Intl.NumberFormat('en-IN',{style:'currency',currency:c,maximumFractionDigits:2}).format(Number(v||0));const up=v=>String(v||'').toUpperCase();
export default function Transactions(){
 const {user}=useAuth(),navigate=useNavigate(),[params]=useSearchParams(),bankId=user?.bankId||user?.bank_id||'alpha',initial=params.get('accountId')||'';
 const [items,setItems]=useState([]),[accounts,setAccounts]=useState([]),[account,setAccount]=useState(initial),[type,setType]=useState('ALL'),[status,setStatus]=useState('ALL'),[q,setQ]=useState(''),[offset,setOffset]=useState(0),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(false),[error,setError]=useState('');const limit=50;
 const load=useCallback(async(silent=false)=>{try{silent?setRefresh(true):setLoading(true);setError('');const qs=new URLSearchParams({limit,offset});if(account)qs.set('accountId',account);const r=await api.get(`/banks/${bankId}/transactions?${qs}`);setItems(r.data?.data?.transactions||[])}catch(e){setError(e.response?.data?.error?.message||'Unable to load transactions.')}finally{silent?setRefresh(false):setLoading(false)}},[bankId,account,offset]);
 useEffect(()=>{load();api.get(`/banks/${bankId}/accounts`).then(r=>setAccounts(r.data?.data?.accounts||[])).catch(()=>{})},[load,bankId]);
 const filtered=useMemo(()=>items.filter(t=>{const text=`${t.transaction_id} ${t.reference||''} ${t.source_account_id||''} ${t.destination_account_id||''}`.toLowerCase();return(type==='ALL'||up(t.type)===type)&&(status==='ALL'||up(t.status)===status)&&(!q||text.includes(q.toLowerCase()))}),[items,q,type,status]);
 return <main className="tx-page"><style>{css}</style><div className="wrap"><header className="top"><div><small>CUSTOMER BANKING</small><h1>Transactions</h1><p>Review your account activity and transaction status.</p></div><button onClick={()=>load(true)} disabled={refresh}><RefreshCw size={16} className={refresh?'spin':''}/> Refresh</button></header>{error&&<div className="error">{error}</div>}
 <div className="filters"><div className="search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search transaction or reference"/></div><select value={account} onChange={e=>{setOffset(0);setAccount(e.target.value)}}><option value="">All accounts</option>{accounts.map(a=><option key={a.account_id} value={a.account_id}>{a.account_type} •••• {String(a.account_number||'').slice(-4)}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)}><option value="ALL">All types</option><option value="TRANSFER">Transfers</option><option value="DEBIT">Debits</option><option value="CREDIT">Credits</option><option value="WITHDRAWAL">Withdrawals</option></select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All status</option><option value="SUCCESS">Success</option><option value="PROCESSING">Processing</option><option value="FAILED">Failed</option></select></div>
 <section className="table"><div className="row head"><span>Transaction</span><span>Type</span><span>Amount</span><span>Status</span><span></span></div>{loading?<div className="empty"><LoaderCircle size={30} className="spin"/></div>:filtered.length===0?<div className="empty"><Wallet size={38}/><h3>No transactions found</h3><p>Try changing the filters.</p></div>:filtered.map(t=>{const debit=['DEBIT','WITHDRAWAL'].includes(up(t.type));return <div className="row" key={t.transaction_id}><div><b>{t.transaction_id}</b><small>{t.reference||'No reference'} · {t.created_at?new Date(t.created_at).toLocaleString('en-IN'):'—'}</small></div><span>{t.type||'Transaction'}</span><strong className={debit?'debit':'credit'}>{debit?'−':'+'}{money(Number(t.amount||0)/100,t.currency)}</strong><span className={`pill ${up(t.status).toLowerCase()}`}>{t.status||'UNKNOWN'}</span><button onClick={()=>navigate(`/transactions/${t.transaction_id}`)}>Details →</button></div>})}</section>
 <footer className="pager"><span>{filtered.length} shown</span><div><button disabled={!offset||loading} onClick={()=>setOffset(v=>Math.max(0,v-limit))}><ChevronLeft size={15}/> Previous</button><button disabled={loading||items.length<limit} onClick={()=>setOffset(v=>v+limit)}>Next <ChevronRight size={15}/></button></div></footer></div></main>
}
const css=`.tx-page{min-height:100vh;background:#f6f8fc;padding:32px;color:#172033}.wrap{max-width:1180px;margin:auto}.top{display:flex;justify-content:space-between;gap:15px;align-items:flex-start;margin-bottom:23px}.top small{font-size:11px;font-weight:800;letter-spacing:.11em;color:#667085}.top h1{font-size:32px;margin:6px 0}.top p{margin:0;color:#667085}.top>button,.pager button{border:1px solid #e4e7ec;background:#fff;border-radius:10px;padding:10px 13px;font-weight:750;cursor:pointer;display:flex;gap:7px;align-items:center}.filters{background:#fff;border:1px solid #e7eaf0;border-radius:16px;padding:14px;display:flex;gap:9px;flex-wrap:wrap;margin-bottom:15px}.search{display:flex;align-items:center;gap:7px;border:1px solid #dfe3e8;border-radius:10px;padding:0 10px;flex:1;min-width:220px}.search input{border:0;outline:0;height:40px;width:100%}.filters select{height:42px;border:1px solid #dfe3e8;border-radius:10px;padding:0 10px;background:#fff}.table{background:#fff;border:1px solid #e7eaf0;border-radius:17px;overflow:hidden}.row{display:grid;grid-template-columns:2fr 1fr 1.2fr 1fr .7fr;gap:13px;align-items:center;padding:16px 19px;border-bottom:1px solid #eef0f3;font-size:13px}.row:last-child{border:0}.head{font-size:10px;text-transform:uppercase;letter-spacing:.06em;color:#98a2b3;font-weight:800;background:#fafbfc}.row b,.row small{display:block}.row small{color:#667085;margin-top:4px;font-size:11px}.row strong{font-size:14px}.debit{color:#b42318}.credit{color:#027a48}.pill{display:inline-flex;width:max-content;border-radius:999px;padding:6px 8px;background:#f2f4f7;color:#475467;font-size:10px;font-weight:850}.pill.success{background:#ecfdf3;color:#027a48}.pill.failed{background:#fef3f2;color:#b42318}.pill.processing{background:#fffaeb;color:#b54708}.row button{border:0;background:none;font-weight:800;cursor:pointer;color:#344054}.empty{text-align:center;padding:55px 20px;color:#667085}.error{background:#fef3f2;color:#b42318;border:1px solid #fecdca;padding:13px;border-radius:12px;margin-bottom:15px}.pager{display:flex;justify-content:space-between;align-items:center;margin-top:13px;color:#667085;font-size:12px}.pager div{display:flex;gap:7px}.spin{animation:spin 1s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}@media(max-width:850px){.tx-page{padding:20px}.top{flex-direction:column}.row{grid-template-columns:1fr 1fr}.head{display:none}}`;
