import {useCallback,useEffect,useState} from 'react';
import {ArrowLeft,CheckCircle2,Clock3,Copy,FileText,LoaderCircle,XCircle} from 'lucide-react';
import {useNavigate,useParams} from 'react-router-dom';import api from '../../services/api';import {useAuth} from '../../context/AuthContext';
const money=(v,c='INR')=>new Intl.NumberFormat('en-IN',{style:'currency',currency:c,maximumFractionDigits:2}).format(Number(v||0));const up=v=>String(v||'').toUpperCase();
export default function TransactionDetails(){const {transactionId}=useParams(),{user}=useAuth(),navigate=useNavigate(),bankId=user?.bankId||user?.bank_id||'alpha';const [tx,setTx]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[copied,setCopied]=useState(false);
 const load=useCallback(async()=>{try{setLoading(true);setError('');const r=await api.get(`/banks/${bankId}/transactions/${transactionId}`);setTx(r.data?.data?.transaction||null)}catch(e){setError(e.response?.data?.error?.message||'Unable to load transaction details.')}finally{setLoading(false)}},[bankId,transactionId]);useEffect(()=>{load()},[load]);
 const copy=async()=>{try{await navigator.clipboard.writeText(transactionId);setCopied(true);setTimeout(()=>setCopied(false),1300)}catch{setError('Unable to copy transaction ID.')}};
 if(loading)return <Shell><div className="card loading"><LoaderCircle className="spin" size={30}/> Loading…</div></Shell>;if(error||!tx)return <Shell><div className="card empty"><h2>Transaction unavailable</h2><p>{error||'Transaction not found.'}</p><button onClick={()=>navigate('/transactions')}><ArrowLeft size={16}/> Back</button></div></Shell>;
 const s=up(tx.status),debit=['DEBIT','WITHDRAWAL'].includes(up(tx.type));return <Shell><style>{css}</style><div className="card"><header><div><small>TRANSACTION DETAILS</small><h1>{tx.type||'Transaction'}</h1><div className="id">{transactionId}<button onClick={copy}><Copy size={13}/></button>{copied&&<em>Copied</em>}</div></div><span className={`status ${s.toLowerCase()}`}>{s==='SUCCESS'?<CheckCircle2 size={15}/>:s==='FAILED'?<XCircle size={15}/>:<Clock3 size={15}/>} {tx.status||'UNKNOWN'}</span></header>
 <div className="hero"><small>TRANSACTION AMOUNT</small><strong className={debit?'debit':'credit'}>{debit?'−':'+'}{money(Number(tx.amount||0)/100,tx.currency)}</strong></div><div className="grid"><Info l="Reference" v={tx.reference||'—'}/><Info l="Type" v={tx.type||'—'}/><Info l="Source account" v={tx.source_account_id||'External / none'}/><Info l="Destination account" v={tx.destination_account_id||'External / none'}/><Info l="Created" v={tx.created_at?new Date(tx.created_at).toLocaleString('en-IN'):'—'}/><Info l="Completed" v={tx.completed_at?new Date(tx.completed_at).toLocaleString('en-IN'):'—'}/></div>
 {tx.failure_reason&&<div className="failure"><b>Failure reason</b><span>{tx.failure_reason}</span></div>}<section className="ledger"><h3><FileText size={17}/> Ledger entries</h3><div className="ledger-box"><div className="lrow lh"><span>Entry</span><span>Account</span><span>Type</span><span>Amount</span></div>{(tx.ledgerEntries||[]).length?(tx.ledgerEntries||[]).map(e=><div className="lrow" key={e.ledger_entry_id}><span>{e.ledger_entry_id}</span><span>{e.account_id}</span><span>{e.entry_type}</span><span>{money(Number(e.amount||0)/100,e.currency)}</span></div>):<p>No ledger entries available.</p>}</div></section><button className="back" onClick={()=>navigate('/transactions')}><ArrowLeft size={16}/> Back to transactions</button>
 </div></Shell>}
function Info({l,v}){return <div className="info"><small>{l}</small><b>{v}</b></div>}function Shell({children}){return <main style={{minHeight:'100vh',background:'#f6f8fc',padding:32,color:'#172033'}}><div style={{maxWidth:980,margin:'auto'}}>{children}</div></main>}
const css=`.card{background:#fff;border:1px solid #e7eaf0;border-radius:20px;padding:27px;box-shadow:0 6px 25px #1018280d}.loading,.empty{min-height:260px;display:grid;place-items:center;text-align:center}.card header{display:flex;justify-content:space-between;gap:15px}.card header small{font-size:11px;letter-spacing:.1em;font-weight:800;color:#667085}.card h1{font-size:29px;margin:5px 0}.id{display:flex;gap:7px;align-items:center;font:12px ui-monospace,monospace}.id button{border:1px solid #e4e7ec;background:#fff;border-radius:7px;padding:5px;cursor:pointer;display:grid}.id em{font-style:normal;color:#027a48}.status{display:flex;gap:6px;align-items:center;height:max-content;border-radius:999px;padding:7px 10px;font-size:10px;font-weight:850;background:#f2f4f7}.status.success{background:#ecfdf3;color:#027a48}.status.failed{background:#fef3f2;color:#b42318}.status.processing{background:#fffaeb;color:#b54708}.hero{background:#111827;color:#fff;border-radius:16px;padding:23px;margin:25px 0}.hero small{font-size:10px;opacity:.7}.hero strong{display:block;font-size:35px;margin-top:5px}.debit{color:#fecaca}.credit{color:#bbf7d0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:13px}.info,.failure{border:1px solid #edf0f4;border-radius:13px;padding:14px}.info small{display:block;color:#98a2b3;font-size:10px;text-transform:uppercase}.info b{display:block;margin-top:6px;word-break:break-word;font-size:13px}.failure{margin-top:13px;background:#fef3f2;border-color:#fecdca}.failure b,.failure span{display:block}.failure span{margin-top:5px;color:#b42318;font-size:13px}.ledger{margin-top:23px}.ledger h3{font-size:16px;display:flex;align-items:center;gap:7px}.ledger-box{border:1px solid #edf0f4;border-radius:13px;overflow:hidden}.lrow{display:grid;grid-template-columns:1.5fr 1fr 1fr 1.1fr;gap:10px;padding:13px;border-bottom:1px solid #edf0f4;font-size:12px}.lrow:last-child{border:0}.lh{font-size:10px;text-transform:uppercase;color:#98a2b3;font-weight:800;background:#fafbfc}.ledger-box>p{padding:20px;color:#667085}.back,.empty button{margin-top:21px;border:1px solid #e4e7ec;background:#fff;border-radius:10px;padding:10px 14px;font-weight:750;cursor:pointer;display:flex;align-items:center;gap:7px}.spin{animation:spin 1s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}@media(max-width:700px){.card header{flex-direction:column}.grid{grid-template-columns:1fr}.lrow{grid-template-columns:1fr 1fr}.lh{display:none}}`;
